[[customizations.user]]
name = "alice"
password = "bob"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCaqQodLAepXMwjg96wMpsKkb8PVoivRwuZa8Iwo57F2vfCBgQBVvpEoHmlB/Un5eFtU5UfzwQPoG5mHpVdtsUetvG/5S6iNm43lFTpHyfJ+26LHiVp42OGbRitqaZ8qJkwe011lPbjG/xOyJhHdAJ59ypdpRgGFS9DhBnA7hpe4+Yl8ZQ85LuEjdWqusNH1WNtB+o1lLMF6ogFoyEXPMw+TEj/T0egixSxFiINW031Q9XxYSh2bnud0LemuwjhJYt/c1uhzmrhbzosKZrWIhCgJ/IQ6Y8uC80kWWEqAgKbNebOU15jNgRMX1bsRGQaH17jAth2ixxenavuOTKvLHN/8pP7rfPXHrOjMyfSfKkjRolKkfZ2TAqqtfwy6EyvSkDN3AHoobmRJImEECo7PQX6n7fqL0WpqB8b+cAP886FX1wOQ6Ik6gjbIAMilKkjAeTupTorPMiw71OD1V+6WZ6BBrdcFChnSARIXBOCq6eWrjsW3QEGg+fQB2HLBV9mbo2TmOGXN+OP0xIxB9LzewZs0z0jm2EIsuXLzG8mTcrgQmSGFc+Wt0ciWA3Gx1yo0WElY1ZUfkziLQ7hr4PRpG34BQylqOkO3d4kS++FUtGkv/FNjAm8E1aP1EYML5YMGWUONnDOB1rSJKbHsXPvAyvogaAOxklYjw38QMu+IOv7Uw== tobias@kerfuffle.club
groups = ["wheel"]

